/*
대장균의 크기에 따라 분류하기 2
SELECT, RANK
*/

SELECT  ID,
        CASE WHEN PER <= 25 THEN 'CRITICAL'
        WHEN PER <= 50 THEN 'HIGH'
        WHEN PER <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM (
SELECT  *,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(1) FROM ECOLI_DATA) * 100 PER
FROM ECOLI_DATA
) AS PER_TABLE
ORDER BY ID;