/*
특정 세대의 대장균 찾기
SELECT
*/

WITH RECURSIVE GEN AS(
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT T2.ID, T2.PARENT_ID, GENERATION+1 GENERATION
    FROM GEN T1 JOIN ECOLI_DATA T2
    ON T1.ID = T2.PARENT_ID
)

SELECT ID
FROM GEN
WHERE GENERATION = 3
ORDER BY 1;