/*
조건에 맞는 사원 정보 조회하기
GROUP BY
*/

WITH CALC_SCORE as (
    SELECT SUM(SCORE) as SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT  SUM(SCORE) as SCORE,
        EMP_NO,
        EMP_NAME,
        POSITION,
        EMAIL
FROM HR_EMPLOYEES LEFT JOIN HR_GRADE
USING (EMP_NO)
GROUP BY EMP_NO
HAVING SUM(SCORE) = (SELECT MAX(SCORE) FROM CALC_SCORE);