/*
노선별 평균 역 사이 거리 조회하기
GROUP BY
*/

SELECT  ROUTE,
        CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') TOTAL_DISTANCE,
        CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY 1
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC;