/*
멸종위기의 대장균 찾기
SELECT
*/

WITH RECURSIVE CTE AS(
    SELECT  ID,
            PARENT_ID,
            1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT  T2.ID,
            T2.PARENT_ID,
            GENERATION+1 AS GENERATION
    FROM CTE AS T1 INNER JOIN ECOLI_DATA T2
    ON T1.ID = T2.PARENT_ID
)

SELECT  COUNT(*) AS "COUNT",
        GENERATION
FROM CTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY 2
ORDER BY 2
;
